#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32

prev = 0.0
pub = None

def callback(mes):
    global prev
    global pub
    if mes.data != prev:
        pub.publish(mes.data)
        prev = mes.data

def main():
	global pub
	pub = rospy.Publisher('battery_lvl_filtered', Float32, queue_size=1)
	rospy.init_node("publisher", anonymous=True)
	rospy.Subscriber("battery_lvl", Float32, callback)
	rospy.spin()

if __name__ == "__main__":
	try:
		main()
	except rospy.ROSInterruptException:
		pass
